# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrank.proto\x12\x11rank_recannnew_pb\"3\n\x07\x44\x61taset\x12(\n\x03msg\x18\x01 \x03(\x0b\x32\x1b.rank_recannnew_pb.MsgClass\"\xb8\x06\n\x08MsgClass\x12<\n\titem_info\x18\x01 \x03(\x0b\x32).rank_recannnew_pb.MsgClass.ItemInfoClass\x12<\n\tuser_info\x18\x02 \x01(\x0b\x32).rank_recannnew_pb.MsgClass.UserInfoClass\x1a\x84\x03\n\rUserInfoClass\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x12\n\nclick_hist\x18\x02 \x03(\t\x12\x11\n\tshow_hist\x18\x03 \x03(\t\x12\x11\n\ttags_hist\x18\x04 \x03(\t\x12\x19\n\x11\x62\x61idu_labels_hist\x18\x05 \x03(\t\x12\x16\n\x0elast_click_nid\x18\x06 \x01(\t\x12\x18\n\x10last_click_title\x18\x07 \x01(\t\x12\x15\n\rcluster_codes\x18\x08 \x03(\t\x12\x11\n\ttitle_emb\x18\t \x03(\t\x12\x0c\n\x04tags\x18\n \x03(\t\x12\x19\n\x11\x63lick_filter_hist\x18\x0b \x03(\t\x12\x18\n\x10show_filter_hist\x18\x0c \x03(\t\x12\x0c\n\x04\x63ity\x18\r \x01(\t\x12\x10\n\x08\x63hannels\x18\x0e \x03(\t\x12\x42\n\x0e\x63urr_item_info\x18\xe8\x07 \x01(\x0b\x32).rank_recannnew_pb.MsgClass.ItemInfoClass\x12\x0e\n\x05patch\x18\xe9\x07 \x03(\x0c\x1a\xa8\x02\n\rItemInfoClass\x12\x10\n\x08is_click\x18\x01 \x01(\t\x12\x0f\n\x07is_show\x18\x02 \x01(\t\x12\x15\n\rcluster_codes\x18\x03 \x03(\t\x12\x11\n\ttitle_emb\x18\x04 \x03(\t\x12\x0b\n\x03nid\x18\x05 \x01(\t\x12\r\n\x05title\x18\x06 \x01(\t\x12\x11\n\trec_start\x18\x07 \x01(\x03\x12\x0f\n\x07rec_end\x18\x08 \x01(\x03\x12\n\n\x02ts\x18\t \x01(\x03\x12\x0f\n\x07\x63ontent\x18\n \x01(\t\x12\x11\n\tcity_code\x18\x0b \x01(\t\x12\x16\n\x0e\x63ity_code_list\x18\x0c \x03(\t\x12\x17\n\x0f\x62\x64_airec_status\x18\r \x01(\t\x12\x0e\n\x05patch\x18\xe9\x07 \x03(\x0c\x12\x19\n\x10qu_default_value\x18\xea\x07 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASET._serialized_start=33
  _DATASET._serialized_end=84
  _MSGCLASS._serialized_start=87
  _MSGCLASS._serialized_end=911
  _MSGCLASS_USERINFOCLASS._serialized_start=224
  _MSGCLASS_USERINFOCLASS._serialized_end=612
  _MSGCLASS_ITEMINFOCLASS._serialized_start=615
  _MSGCLASS_ITEMINFOCLASS._serialized_end=911
# @@protoc_insertion_point(module_scope)
