# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrank.proto\x12\x07rank_pb\")\n\x07\x44\x61taset\x12\x1e\n\x03msg\x18\x01 \x03(\x0b\x32\x11.rank_pb.MsgClass\"\xf2\x02\n\x08MsgClass\x12\x32\n\tuser_info\x18\x01 \x01(\x0b\x32\x1f.rank_pb.MsgClass.UserInfoClass\x12\x32\n\titem_info\x18\x02 \x03(\x0b\x32\x1f.rank_pb.MsgClass.ItemInfoClass\x1a\x43\n\rUserInfoClass\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x12\n\nclick_hist\x18\x02 \x03(\t\x12\x11\n\tshow_hist\x18\x03 \x03(\t\x1a\xb8\x01\n\rItemInfoClass\x12\x10\n\x08is_click\x18\x01 \x01(\t\x12\x0f\n\x07is_show\x18\x02 \x01(\t\x12\x0b\n\x03nid\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x03(\t\x12\r\n\x05\x63olor\x18\x06 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x07 \x01(\t\x12\x0b\n\x03num\x18\x08 \x01(\t\x12\x0c\n\x04\x61rea\x18\t \x01(\t\x12\x17\n\x0f\x62\x64_airec_status\x18\n \x01(\t')



_DATASET = DESCRIPTOR.message_types_by_name['Dataset']
_MSGCLASS = DESCRIPTOR.message_types_by_name['MsgClass']
_MSGCLASS_USERINFOCLASS = _MSGCLASS.nested_types_by_name['UserInfoClass']
_MSGCLASS_ITEMINFOCLASS = _MSGCLASS.nested_types_by_name['ItemInfoClass']
Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), {
  'DESCRIPTOR' : _DATASET,
  '__module__' : 'rank_pb2'
  # @@protoc_insertion_point(class_scope:rank_pb.Dataset)
  })
_sym_db.RegisterMessage(Dataset)

MsgClass = _reflection.GeneratedProtocolMessageType('MsgClass', (_message.Message,), {

  'UserInfoClass' : _reflection.GeneratedProtocolMessageType('UserInfoClass', (_message.Message,), {
    'DESCRIPTOR' : _MSGCLASS_USERINFOCLASS,
    '__module__' : 'rank_pb2'
    # @@protoc_insertion_point(class_scope:rank_pb.MsgClass.UserInfoClass)
    })
  ,

  'ItemInfoClass' : _reflection.GeneratedProtocolMessageType('ItemInfoClass', (_message.Message,), {
    'DESCRIPTOR' : _MSGCLASS_ITEMINFOCLASS,
    '__module__' : 'rank_pb2'
    # @@protoc_insertion_point(class_scope:rank_pb.MsgClass.ItemInfoClass)
    })
  ,
  'DESCRIPTOR' : _MSGCLASS,
  '__module__' : 'rank_pb2'
  # @@protoc_insertion_point(class_scope:rank_pb.MsgClass)
  })
_sym_db.RegisterMessage(MsgClass)
_sym_db.RegisterMessage(MsgClass.UserInfoClass)
_sym_db.RegisterMessage(MsgClass.ItemInfoClass)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASET._serialized_start=23
  _DATASET._serialized_end=64
  _MSGCLASS._serialized_start=67
  _MSGCLASS._serialized_end=437
  _MSGCLASS_USERINFOCLASS._serialized_start=183
  _MSGCLASS_USERINFOCLASS._serialized_end=250
  _MSGCLASS_ITEMINFOCLASS._serialized_start=253
  _MSGCLASS_ITEMINFOCLASS._serialized_end=437
# @@protoc_insertion_point(module_scope)
